Move validation

diff --git a/.github/workflows/e2e-deploy.yml b/.github/workflows/e2e-deploy.yml
--- a/.github/workflows/e2e-deploy.yml
+++ b/.github/workflows/e2e-deploy.yml
@@ -11,8 +11,6 @@ on:
 jobs:
   run_action:
     runs-on: ubuntu-latest
-    outputs:
-      results: ${{ steps.fetchResult.outputs.response }}
     steps:
       - uses: actions/checkout@v3
       - name: Bump test plugin version number
@@ -35,12 +33,15 @@ jobs:
         uses: fjogeleit/http-request-action@v1
         with:
           url: "https://apmdomino.wpengine.com/wp-content/plugins/status.json"
-  validate_result:
-    runs-on: ubuntu-latest
-    if: ${{ !cancelled() }}
-    needs: run_action
-    steps:
       - name: Validate deploy results
-        if: ${{ needs.run_action.result == 'success' }} 
         run: |
-          [ ${{ fromJson(needs.run_action.outputs.results).status }} = "success" ] || exit 1
+          [ ${{ fromJson(steps.fetchResult.outputs.response).status }} = "success" ] || exit 1
+  notify:
+    runs-on: ubuntu-latest
+    needs: run_action
+    if: ${{ needs.run_action.result == 'failure' }} && github.ref == 'refs/heads/main'
+    steps:
+      - name: Notify slack on failure
+        run: |
+          echo "Job failed. Notifying slack channel."
+      
